name: Continuous integration
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Retrieve the content of the repository
      - uses: actions/setup-java@v3 # Set up a jdk
        with:
          distribution: temurin
          java-version: 17
          cache: sbt # Cache the artifacts downloaded by sbt accross CI runs

      - name: Linting
        run: |
          cd library; sbt "scalafixAll --check"; cd ..
          cd service-a; sbt "scalafixAll --check"; cd ..
          cd service-b; sbt "scalafixAll --check"; cd ..
      - name: Code style
        run: |
          cd library; sbt scalafmtCheck; cd ..
          cd library; sbt scalafmtCheck; cd ..
          cd library; sbt scalafmtCheck; cd ..

      - name: Run library tests
        run: cd library; sbt +test
      - name: Run service a tests
        run: cd service-a; sbt +test
      - name: Run service-b tests
        run: cd service-b; sbt +test
        
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags, required to compute the release version
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: cd library; sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
